basic:
    name: venturacounty.gov
    environments:
        production: 'https://www.ventura.org/'
        staging: 'https://venturacounty.gov/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - board-of-supervisors
        - board-of-supervisors/district-1
        - board-of-supervisors/district-2-jeff-gorell
        - board-of-supervisors/district-3-kelly-long
        - board-of-supervisors/district-4-janice-parvin
        - board-of-supervisors/district-5
        - districtmaps
        - board-of-supervisors/redistricting
        - board-of-supervisors/agendas-documents-and-broadcasts
        - government/administration
        - county-executive-office/budget-and-finance
        - government/city-governments
        - government/county-strategy-performance-budget
        - county-executive-office/dei
        - departments
        - government/downloadable-forms
        - government/elected-officials
        - yellow-pages
        - government/find-our-offices
        - maps
        - government/contact-the-county
        - government/meetings-and-broadcasts
        - government/mission-statement
        - government/plans-studies-and-ordinances
        - ttc
        - sb-272
        - auditor-controllers-office/tax-rate-database
        - agricultural-commissioner
        - auditor-controllers-office
        - child-support-services
        - civil-service-commission
        - county-executive-office
        - general-services-agency
        - grand-jury
        - harbor-department
        - human-services-agency
        - itsd
        - parks-department
        - human-services-agency/adult-senior-services
        - child-and-youth-services
        - health-and-human-services/crisis-and-emergency-services
        - health-and-human-services/employment-financial-assistance
        - health-and-human-services/food-assistance-and-healthy-eating
        - health-and-human-services/program-and-services-directory
        - human-services-agency/homeless-services
        - human-services-agency/veteran-services
        - business-services/become-a-vendor
        - business-services/business-assistance-and-resources
        - business-services/emergency-preparedness-for-business
        - business-services/employment-training-and-education
        - business-services/licenses-regulations-and-permits
        - business-services/start-a-business
        - business-services/taxes-and-the-assessors-office
        - auditor-controllers-office/fraud-hotline
        - employment/youth-employment
        - residents/animal-pets
        - residents/certificates-registration-records
        - residents/consumer-rights-protection
        - residents/education
        - residents/housing
        - residents/public-safety-and-courts
        - county-executive-office/psreag
        - human-services-agency/homeless-shelters
        - residents/social-services
        - residents/taxes-fines-fees-permits
        - residents/voting
        - visitors/campgrounds
        - parks
        - visitors/transportation
        - visitors/things-to-do-in-each-community
        - visitors/visitor-convention-bureaus
        - environment/air-quality
        - environment/drive-clean
        - environment/energy-efficiency
        - environment/environmental-health
        - environment/going-green
        - environment/graffiti-removal
        - environment/green-building
        - environment/planning-and-land-use
        - environment/waste-and-recycling
        - environment/water-quality
        - agricultural-commissioner/save-our-food
        - online-services
        - ambulance-rfp
        - ssfl
        - truth_act
        - vcsafe
        - county-executive-office/assessment-appeals
        - residents/where-do-county-government-funds-come-from
        - find
        - dispose-of
        - requestapply
        - report-a-concern
        - pay
        - parks-department/beach-front-parks/rincon-parkway
        - parks-department/beach-front-parks/faria-beach-park
        - ttc/pay-your-taxes
        - parks-department/reservations
        - human-services-agency/medi-cal
        - child-support-services/outreach-services
        - americanrescueplan
        - county-executive-office/service-excellence
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
